import { assetUrl } from './preview';
export type CategoryId = 'foundation' | 'lifting' | 'concrete' | 'road' | 'earthmoving' | 'handling';
export type Equipment = { id: string; name: string; brand: string; category: CategoryId; type: string; image: string; description: string; features: string[]; specs: { label: string; value: string }[]; source: string; featured?: boolean };
export const categories = [
  { id: 'foundation' as CategoryId, name: 'Foundation', full: 'Foundation equipment', image: assetUrl('/images/foundation.webp'), title: 'Great projects start below the surface.', description: 'Piling rigs and vibro hammers for the foundations that carry bridges, metros and the next generation of infrastructure.' },
  { id: 'lifting' as CategoryId, name: 'Lifting', full: 'Lifting equipment', image: assetUrl('/images/lifting.webp'), title: 'Raise the possibilities.', description: 'Crawler cranes, all-terrain cranes and access equipment for demanding lifting and installation work.' },
  { id: 'concrete' as CategoryId, name: 'Concrete', full: 'Concrete equipment', image: assetUrl('/images/concrete.webp'), title: 'Put your plans into concrete.', description: 'Concrete pumping equipment that keeps material moving through the critical stages of construction.' },
  { id: 'road' as CategoryId, name: 'Road construction', full: 'Road construction', image: assetUrl('/images/road.webp'), title: 'Every kilometre moves us forward.', description: 'Pavers, compactors and graders for highways, expressways and the connections between communities.' },
  { id: 'earthmoving' as CategoryId, name: 'Earthmoving', full: 'Earthmoving equipment', image: assetUrl('/images/earthmoving.webp'), title: 'Make room for what comes next.', description: 'Excavators, dozers and loaders for site preparation, excavation and heavy material movement.' },
  { id: 'handling' as CategoryId, name: 'Material handling', full: 'Material handling', image: assetUrl('/images/handling.webp'), title: 'Keep the whole site moving.', description: 'Wheel loaders, telehandlers and backhoe loaders for the everyday work that makes extraordinary projects possible.' }
];
const makeEquipment = (id: string, name: string, brand: string, category: CategoryId, type: string, description: string, features: string[], extra: { label: string; value: string }[] = []): Equipment => ({ id, name, brand, category, type, image: assetUrl(`/images/${category}.webp`), description, features, specs: [{ label: 'Manufacturer', value: brand }, { label: 'Equipment type', value: type }, { label: 'Service', value: 'Project rental' }, ...extra], source: `https://aggconequipments.com/${category === 'foundation' ? 'pilling-ring' : category === 'lifting' ? 'crawler-crane' : category === 'earthmoving' ? 'excavator' : category === 'concrete' ? 'boom-pump' : category === 'handling' ? 'loader' : 'soil-compactor'}/` });
export const equipment: Equipment[] = [
  makeEquipment('mait-hr180', 'MAIT HR 180', 'MAIT', 'foundation', 'Rotary piling rig', 'A rotary piling rig from AGGCON’s published foundation fleet, for deep-foundation construction requirements.', ['Foundation works', 'Crawler-mounted machinery', 'Operator support available', 'Configuration confirmed for your project']),
  makeEquipment('sany-sr285r', 'SANY SR285R', 'SANY', 'foundation', 'Rotary piling rig', 'Foundation equipment for demanding infrastructure sites, supported by project deployment and maintenance teams.', ['Deep foundations', 'Infrastructure deployment', 'Planned maintenance support']),
  makeEquipment('xcmg-xr280d', 'XCMG XR280D', 'XCMG', 'foundation', 'Rotary piling rig', 'A heavy foundation machine featured in AGGCON’s published equipment fleet.', ['Piling applications', 'Crawler-mounted platform', 'Project rental support']),
  makeEquipment('xcmg-crawler400', 'XCMG Crawler Crane', 'XCMG', 'lifting', 'Crawler crane', 'A 400-tonne crane listed in AGGCON’s lifting fleet. Lift configuration and suitability are confirmed against your project requirements.', ['Heavy lifting', 'Crawler-mounted platform', 'Installation and erection works'], [{ label: 'Listed capacity', value: '400 tonnes' }]),
  makeEquipment('ace-acx750', 'ACE ACX 750', 'ACE', 'lifting', 'Crawler crane', 'Crawler crane rental for construction lifting, with project-specific deployment planning.', ['Construction lifting', 'Operator coordination', 'Site deployment planning']),
  makeEquipment('electric-scissor', 'S4550E Electric Scissor Lift', 'To be confirmed', 'lifting', 'Scissor lift', 'Electric access equipment for work at height. The published AGGCON listing specifies a 15.8 m working height.', ['Electric drive', 'Indoor access applications', 'Low-noise operation'], [{ label: 'Working height', value: '15.80 m' }, { label: 'Platform capacity', value: '227 kg' }]),
  makeEquipment('schwing-s36sx', 'Schwing Stetter S 36 SX', 'Schwing Stetter', 'concrete', 'Concrete boom pump', 'Truck-mounted concrete pumping machinery from AGGCON’s published concrete equipment fleet.', ['Concrete placement', 'Truck-mounted boom', 'Project maintenance support']),
  makeEquipment('putzmeister-bsf425', 'Putzmeister BSF 42-5', 'Putzmeister', 'concrete', 'Concrete boom pump', 'Concrete boom pump rental for infrastructure and building projects.', ['Concrete pumping', 'Boom placement', 'On-site coordination']),
  makeEquipment('case-1107', 'CASE 1107-EX D', 'CASE', 'road', 'Soil compactor', 'Compaction equipment listed in AGGCON’s road construction fleet.', ['Road construction', 'Soil compaction', 'Ground preparation']),
  makeEquipment('vogele-super1800', 'Vögele Super 1800-3', 'Vögele', 'road', 'Tracked paver', 'Paving machinery for road construction and highway development requirements.', ['Asphalt paving', 'Road and highway works', 'Deployment support']),
  makeEquipment('kobelco-sk500', 'Kobelco SK 500HDLC', 'Kobelco', 'earthmoving', 'Crawler excavator', 'A crawler excavator featured in AGGCON’s earthmoving fleet for excavation and material movement.', ['Heavy excavation', 'Site preparation', 'Crawler-mounted platform']),
  makeEquipment('jcb-excavator', 'JCB Excavator', 'JCB', 'earthmoving', 'Excavator', 'Excavator rental for construction and infrastructure sites. Model configuration is confirmed during your enquiry.', ['Excavation', 'Site preparation', 'Project-specific configuration']),
  makeEquipment('jcb-430zx', 'JCB 430ZX Plus', 'JCB', 'handling', 'Wheel loader', 'Wheel loader rental for site material handling and loading applications.', ['Material handling', 'Bulk loading', 'Site logistics']),
  makeEquipment('jcb-3dx', 'JCB 3DX', 'JCB', 'handling', 'Backhoe loader', 'A versatile backhoe loader in AGGCON’s published material handling fleet.', ['Loading and excavation', 'Site utility work', 'Project rental support']),
  makeEquipment('oms-vibro', 'OMS 8 Ton Vibro Hammer', 'OMS', 'foundation', 'Vibro hammer', 'An OMS vibro hammer listed in AGGCON’s foundation equipment range.', ['Foundation equipment', 'Project configuration confirmed on enquiry']),
  makeEquipment('xcmg-atc', 'XCMG ATC Crane', 'XCMG', 'lifting', 'All-terrain crane', 'An all-terrain crane from AGGCON’s published lifting fleet.', ['Lifting equipment', 'Lift plan and configuration confirmed on enquiry']),
  makeEquipment('sany-crawler', 'SANY Crawler Crane', 'SANY', 'lifting', 'Crawler crane', 'SANY crawler crane equipment listed by AGGCON.', ['Lifting equipment', 'Lift plan and configuration confirmed on enquiry']),
  makeEquipment('putzmeister-bsf364', 'Putzmeister BSF 36-4', 'Putzmeister', 'concrete', 'Concrete boom pump', 'A Putzmeister concrete boom pump listed in AGGCON’s fleet.', ['Concrete placement', 'Project configuration confirmed on enquiry']),
  makeEquipment('schwing-s46sx', 'Schwing Stetter S 46 SX', 'Schwing Stetter', 'concrete', 'Concrete boom pump', 'Schwing Stetter concrete pumping equipment from AGGCON’s published range.', ['Concrete placement', 'Project configuration confirmed on enquiry']),
  makeEquipment('case-752', 'CASE 752 Vibro Tandem Roller', 'CASE', 'road', 'Tandem roller', 'A CASE tandem roller listed in AGGCON’s road construction fleet.', ['Road construction', 'Project configuration confirmed on enquiry']),
  makeEquipment('dozer', 'Dozer', 'To be confirmed', 'earthmoving', 'Dozer', 'Dozer equipment is included in AGGCON’s earthmoving range. Manufacturer and model are confirmed against your requirement.', ['Earthmoving equipment', 'Model confirmed on enquiry']),
  makeEquipment('jcb-skid-steer', 'JCB Skid Steer Loader', 'JCB', 'earthmoving', 'Skid steer loader', 'A JCB skid steer loader listed in AGGCON’s earthmoving range.', ['Earthmoving equipment', 'Project configuration confirmed on enquiry']),
  makeEquipment('hm-2021', 'HM 2021', 'HM', 'handling', 'Loader', 'HM 2021 loader equipment listed in AGGCON’s material handling range.', ['Material handling', 'Project configuration confirmed on enquiry']),
  makeEquipment('telehandler', 'Telehandler', 'To be confirmed', 'handling', 'Telehandler', 'Telehandler equipment is included in AGGCON’s material handling range. Manufacturer and model are confirmed on enquiry.', ['Material handling', 'Model confirmed on enquiry'])
];
for (const e of equipment) {
  if (e.id === 'electric-scissor') e.source = 'https://aggconequipments.com/scissor-lift/';
  if (['sany-sr285r','oms-vibro','jcb-skid-steer','telehandler','sany-crawler','xcmg-atc'].includes(e.id)) e.source = 'https://aggconequipments.com/';
}
export type Project = { id: string; name: string; sector: string; location: string; image: string; title: string; description: string; role: string; categories: CategoryId[]; client?: string; source: string };
export const projects: Project[] = [
  { id: 'atal-setu', name: 'Atal Setu', sector: 'Bridges', location: 'Mumbai, Maharashtra', image: assetUrl('/images/atal-setu.webp'), title: 'Connecting more than two shores.', description: 'The Mumbai Trans Harbour Link connects Mumbai and Navi Mumbai across the harbour. AGGCON’s published project account describes its contribution to foundation work through rental machinery and operators.', role: 'Rental machinery and operators for foundation and other construction work.', categories: ['foundation', 'lifting'], client: 'L&T Construction', source: 'https://aggconequipments.com/projects/' },
  { id: 'yamuna-expressway', name: 'Yamuna Expressway', sector: 'Highways', location: 'Uttar Pradesh', image: assetUrl('/images/yamuna.webp'), title: 'A road to new possibilities.', description: 'A major connection between Greater Noida and Agra. AGGCON describes supporting contractors with heavy construction equipment during the project.', role: 'Heavy construction equipment supplied to project contractors.', categories: ['road', 'earthmoving'], source: 'https://aggconequipments.com/projects/' },
  { id: 'hyderabad-metro', name: 'Hyderabad Metro', sector: 'Urban infrastructure', location: 'Hyderabad, Telangana', image: assetUrl('/images/hyderabad.webp'), title: 'Moving a city forward.', description: 'A landmark urban transport development. AGGCON’s project portfolio records its involvement through the provision of heavy construction equipment.', role: 'Heavy construction equipment support.', categories: ['foundation', 'concrete'], source: 'https://aggconequipments.com/projects/' },
  { id: 'kochi-metro', name: 'Kochi Metro', sector: 'Urban infrastructure', location: 'Kochi, Kerala', image: assetUrl('/images/metro.webp'), title: 'Infrastructure that brings people closer.', description: 'AGGCON includes Kochi Metro in its portfolio of infrastructure projects supported by construction equipment.', role: 'Construction equipment rental support.', categories: ['foundation', 'concrete'], source: 'https://aggconequipments.com/projects/' }
];
projects.push({ id: 'ganga-river-bridge', name: 'Ganga River Bridge', sector: 'Bridges', location: 'Ballia, Uttar Pradesh', image: assetUrl('/images/ganga.webp'), title: 'Connecting communities across the Ganga.', description: 'AGGCON’s published portfolio includes the Ganga River Bridge project at Ballia, supported through heavy construction equipment.', role: 'Heavy construction equipment supplied to the project.', categories: ['foundation', 'lifting'], source: 'https://aggconequipments.com/projects/' });
export const industries = [
  { id: 'bridges', title: 'Bridges & deep foundations', text: 'The machinery and support behind demanding foundation and structural construction work.', categories: ['foundation','lifting'] as CategoryId[], image: assetUrl('/images/atal-setu.webp') },
  { id: 'highways', title: 'Roads & highways', text: 'Equipment for preparing, paving and connecting the country, kilometre after kilometre.', categories: ['road','earthmoving'] as CategoryId[], image: assetUrl('/images/yamuna.webp') },
  { id: 'urban', title: 'Metro & urban infrastructure', text: 'Project machinery for the systems that help growing cities move.', categories: ['foundation','concrete','handling'] as CategoryId[], image: assetUrl('/images/metro.webp') },
  { id: 'energy', title: 'Energy & industrial projects', text: 'Lifting and handling solutions for installation, industrial construction and wind-turbine erection.', categories: ['lifting','handling'] as CategoryId[], image: assetUrl('/images/lifting.webp') }
];
export const resources = [
  { title: 'Disclosures under Regulation 46', group: 'Governance', year: 'Current', href: 'https://aggconequipments.com/itemsunderregulation/', kind: 'Website' },
  { title: 'Material contracts and documents', group: 'Reports', year: 'Current', href: 'https://aggconequipments.com/material-contracts-and-documents/', kind: 'Website' },
  { title: 'Restated consolidated financial information', group: 'Financial information', year: '2025', href: 'https://aggconequipments.com/wp-content/uploads/2025/07/Aggcon-Restated-Consolidated-2025.pdf', kind: 'PDF' },
  { title: 'Restated standalone financial information', group: 'Financial information', year: '2025', href: 'https://aggconequipments.com/wp-content/uploads/2025/07/Aggcon-Restated-Standalone-2025.pdf', kind: 'PDF' },
  { title: 'Board committees & mandates', group: 'Governance', year: 'Current', href: 'https://aggconequipments.com/investors-2/', kind: 'Website' },
  { title: 'Company policies & guidelines', group: 'Governance', year: 'Current', href: 'https://aggconequipments.com/companypoliciesandguidelines/', kind: 'Website' },
  { title: 'Shareholder composition', group: 'Shareholders', year: 'Current', href: 'https://aggconequipments.com/shareholdercomposition/', kind: 'Website' },
  { title: 'Industry report', group: 'Reports', year: 'Current', href: 'https://aggconequipments.com/industryreport/', kind: 'Website' },
  { title: 'IPO information & offer documents', group: 'Reports', year: '2025', href: 'https://aggconequipments.com/ipo/', kind: 'Website' }
];
export const company = { name: 'AGGCON Equipments International Limited', phone: '+91 88004 92290', tel: '+918800492290', email: 'info@aggconequipments.in', corporate: '1333 (LGF), Sector 28, Faridabad, Haryana 121008', registered: 'Unit E 009, Tower E, Ground Floor, World Trade Center, Nauroji Nagar, New Delhi 110029' };

export function machinePhotoNote(machine:Equipment){return machine.id==='sany-sr285r'?'Illustrative piling rig':machine.id==='jcb-excavator'?'Excavator category photo':['electric-scissor','dozer','telehandler'].includes(machine.id)?'Equipment type illustration':'';}
