import { chromium, expect } from '@playwright/test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import path from 'node:path';

const base = process.env.PREVIEW_URL || 'http://127.0.0.1:3001';
const review = path.resolve('.impeccable/review');
await mkdir(review, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
const errors = [], results = [];
const email = `qa-${Date.now()}@preview.example`;
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.setDefaultTimeout(12000);
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error' && !m.text().includes('401')) errors.push(m.text()); });
async function route(url) {
  const response = await page.goto(base + url);
  expect(response.status()).toBe(200);
  await page.locator('h1').first().waitFor();
  await page.evaluate(async () => { await document.fonts.ready; await Promise.all([...document.images].filter(i => i.loading !== 'lazy').map(i => i.decode().catch(() => {}))); });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy();
  results.push(`Loaded ${url}`);
}
async function capture(name) {
  if (process.env.CAPTURE_REVIEW !== 'true') return;
  await page.evaluate(async () => { for (const i of document.images) i.loading = 'eager'; await Promise.all([...document.images].map(i => i.decode().catch(() => {}))); scrollTo(0, 0); });
  expect(await page.locator('img').evaluateAll(imgs => imgs.every(i => i.complete && i.naturalWidth > 0))).toBeTruthy();
  if(process.env.CAPTURE_REVIEW === 'true') await page.screenshot({ path: `${review}/${name}.png`, fullPage: true, animations: 'disabled' });
}
try {
  await route('/');
  await capture('desktop');
  if(process.env.CAPTURE_REVIEW === 'true') await page.screenshot({ path: `${review}/desktop-hero.png`, animations: 'disabled' });
  await page.getByRole('tab', { name: 'Lifting' }).click();
  await expect(page.getByRole('tabpanel')).toContainText('lifting');
  await page.getByRole('button', { name: 'Search equipment and projects' }).click();
  await page.getByRole('textbox', { name: 'Search equipment or projects' }).fill('MAIT');
  await page.locator('.search-results').getByRole('link', { name: /MAIT/ }).click();
  await expect(page).toHaveURL(/equipment\/mait-hr180/);
  await page.getByRole('button', { name: 'Add MAIT HR 180 to quote' }).click();
  await route('/equipment');
  await page.getByRole('textbox', { name: 'Search equipment catalogue' }).fill('zzzz-empty');
  await expect(page.getByRole('heading', { name: 'Let’s try a different search.' })).toBeVisible();
  await page.getByRole('button', { name: 'Reset filters' }).click();
  await expect(page.locator('.machine-card')).toHaveCount(24);
  await page.getByRole('button', { name: /^Road/ }).click();
  await expect(page.locator('.machine-card')).toHaveCount(3);
  await route('/quote');
  await expect(page.locator('.quote-machine')).toHaveCount(1);
  await page.getByRole('button', { name: 'Increase MAIT HR 180 quantity' }).click();
  await expect(page.locator('.quantity-control')).toContainText('2');
  await page.reload();
  await expect(page.locator('.quantity-control')).toContainText('2');
  await page.getByRole('button', { name: 'Project details', exact: true }).click();
  await page.locator('input[name=location]').fill('Faridabad, Haryana');
  await page.locator('textarea[name=message]').fill('Synthetic preview QA enquiry. No external message should be sent.');
  await page.getByRole('button', { name: 'Your details', exact: true }).click();
  await page.locator('input[name=name]').fill('Preview QA');
  await page.locator('input[name=company]').fill('Preview Test Company');
  await page.locator('input[name=email]').fill(email);
  await page.locator('input[name=phone]').fill('+91 9000000000');
  await page.locator('input[name=consent]').check();
  await page.getByRole('button', { name: 'Send project enquiry' }).click();
  await expect(page.locator('.quote-success')).toBeVisible();
  const reference = await page.locator('.reference-box strong').textContent();
  expect(reference).toMatch(/^AG-\d{4}-[A-F0-9]{8}$/);
  results.push('Catalogue search, category filters, shortlist persistence, quantity and complete quote submission passed');
  await route('/contact');
  await page.locator('input[name=location]').fill('Delhi');
  await page.locator('input[name=name]').fill('Preview QA');
  await page.locator('input[name=company]').fill('Preview Test Company');
  await page.locator('input[name=email]').fill(email);
  await page.locator('input[name=phone]').fill('9000000000');
  await page.locator('input[name=consent]').check();
  await page.getByRole('button', { name: 'Send your message' }).click();
  await expect(page.locator('.quote-success')).toBeVisible();
  results.push('Contact form submission passed');
  const anonymous = await context.request.get(base + '/api/admin');
  expect(anonymous.status()).toBe(401);
  const invalid = await context.request.post(base + '/api/quotes', { headers: { Origin: base }, data: { name: 'x' } });
  expect(invalid.status()).toBe(400);
  const crossOrigin = await context.request.post(base + '/api/quotes', { headers: { Origin: 'https://example.com' }, data: {} });
  expect(crossOrigin.status()).toBe(403);
  await route('/admin');
  const local = await readFile('.env.local', 'utf8');
  const passphrase = local.match(/^ADMIN_PASSWORD=(.+)$/m)?.[1];
  expect(Boolean(passphrase)).toBeTruthy();
  await page.getByLabel('Admin passphrase').fill(passphrase);
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page.locator('.admin-tools')).toBeVisible();
  await page.getByRole('textbox', { name: 'Search enquiries' }).fill(email);
  await expect(page.locator('.enquiry-card')).toHaveCount(2);
  await page.getByLabel(`Status for ${reference}`).selectOption('Contacted');
  await expect(page.getByLabel(`Status for ${reference}`)).toHaveValue('Contacted');
  await page.reload();
  await expect(page.getByLabel(`Status for ${reference}`)).toHaveValue('Contacted');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export CSV' }).click();
  expect((await downloadPromise).suggestedFilename()).toBe('aggcon-enquiries.csv');
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page.getByLabel('Admin passphrase')).toBeVisible();
  expect((await context.request.get(base + '/api/admin')).status()).toBe(401);
  results.push('Private admin authentication, database persistence, enquiry status, CSV download and logout passed');
  for (const url of ['/projects','/projects/atal-setu','/company','/industries','/investors','/sustainability','/news','/buy','/privacy']) await route(url);
  await route('/');
  await page.setViewportSize({ width: 390, height: 844 });
  await capture('mobile');
  if(process.env.CAPTURE_REVIEW === 'true') await page.screenshot({ path: `${review}/mobile-hero.png`, animations: 'disabled' });
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('navigation', { name: 'Mobile navigation' }).getByRole('link', { name: 'Equipment' }).click();
  await expect(page).toHaveURL(/\/equipment/);
  await capture('mobile-fleet');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy();
  await page.getByRole('button', { name: 'Filters', exact: true }).click();
  await page.getByRole('button', { name: /^Lifting/ }).click();
  await expect(page.locator('.machine-card')).toHaveCount(5);
  results.push('Mobile navigation, catalogue and filters passed at 390px');
  expect(errors).toEqual([]);
  const verifiedErrors=[...errors];
  const missing = await page.goto(base + '/not-a-real-page');
  expect(missing.status()).toBe(404);
  await expect(page.getByRole('heading', { name: /BACK ON TRACK/ })).toBeVisible();
  await writeFile(`${review}/functional-check.json`, JSON.stringify({ base, passed: true, results, browserErrors: verifiedErrors, expectedNotFoundStatus: 404 }, null, 2));
  console.log(JSON.stringify({ passed: true, checks: results.length, screenshots: review, browserErrors: verifiedErrors, expectedNotFoundStatus: 404 }, null, 2));
} finally {
  await browser.close();
  try { const db = new DatabaseSync(path.resolve('data/aggcon.sqlite')); db.prepare('DELETE FROM enquiries WHERE email = ? AND company = ?').run(email, 'Preview Test Company'); db.close(); } catch {}
}
