import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowUpRight, Check, ArrowLeft, FileText, HardHat, Wrench, Truck } from 'lucide-react';
import { equipment, categories, machinePhotoNote } from '@/lib/data';
import { AddToQuote } from '@/components/Chrome';
import { MachineImage } from '@/components/Fleet';
export function generateStaticParams(){return equipment.map(e=>({slug:e.id}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const e=equipment.find(e=>e.id===slug);return {title:e?.name||'Equipment',description:e?.description};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const machine=equipment.find(e=>e.id===slug);if(!machine)notFound();const category=categories.find(c=>c.id===machine.category)!;return <div className="equipment-detail container"><Link href={`/equipment?category=${machine.category}`} className="back-link"><ArrowLeft size={16}/> {category.full}</Link><div className="detail-grid"><div className="detail-photo"><MachineImage machine={machine}/><span>{machinePhotoNote(machine)||'AGGCON published fleet photography'}</span></div><div className="detail-copy"><h1>{machine.name}</h1><span className="detail-type">{machine.type}</span><p className="large-copy">{machine.description}</p><dl className="spec-table">{machine.specs.map(s=><div key={s.label}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl><AddToQuote id={machine.id}/><Link href="/quote" className="inline-link detail-enquire">Discuss your project <ArrowUpRight size={18}/></Link><p className="detail-note">Availability, specifications and the exact machine configuration are confirmed for your project.</p></div></div><div className="detail-bottom"><div><h2>READY FOR THE WORK AHEAD.</h2><ul className="feature-list">{machine.features.map(f=><li key={f}><Check size={18}/>{f}</li>)}</ul><a href={machine.source} target="_blank" rel="noreferrer" className="inline-link">View the published fleet source <ArrowUpRight size={17}/></a></div><div className="detail-support"><h3>More than the machine.</h3><p>Talk to AGGCON about the support your project needs.</p><div><HardHat size={21}/> Operator requirements</div><div><Wrench size={21}/> Maintenance coordination</div><div><Truck size={21}/> Site deployment</div></div></div><div className="related-section"><div className="section-heading"><h2>KEEP EXPLORING.</h2><Link href={`/equipment?category=${machine.category}`} className="inline-link">All {category.name.toLowerCase()} <ArrowUpRight size={17}/></Link></div><div className="related-machines">{equipment.filter(e=>e.category===machine.category&&e.id!==machine.id).slice(0,3).map(e=><Link href={`/equipment/${e.id}`} key={e.id}><MachineImage machine={e}/><span>{e.name}<ArrowUpRight size={20}/></span></Link>)}</div></div></div>;}
