'use client';
import { useState, useEffect } from 'react';
import { ArrowRight, ArrowDownToLine, LockKeyhole, Search, LogOut, ChevronDown, Loader2 } from 'lucide-react';
type Enquiry={id:string;created_at:string;kind:string;name:string;email:string;phone:string;company:string;location:string;start_date:string;duration:string;message:string;items:string;status:string};
export function Admin(){const [rows,setRows]=useState<Enquiry[]>([]);const [auth,setAuth]=useState(false);const [loading,setLoading]=useState(true);const [password,setPassword]=useState('');const [error,setError]=useState('');const [query,setQuery]=useState('');const [status,setStatus]=useState('All');const [selected,setSelected]=useState('');
  async function load(){try{const r=await fetch('/api/admin',{cache:'no-store'});if(r.status===401){setAuth(false);return;}const d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.enquiries);setAuth(true);}catch(e){setError(e instanceof Error?e.message:'Could not load enquiries.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function login(e:React.FormEvent){e.preventDefault();setError('');setLoading(true);try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPassword('');await load();}catch(e){setError(e instanceof Error?e.message:'Could not sign in.');setLoading(false);}}
  async function update(id:string,value:string){setError('');try{const r=await fetch('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:value})});if(!r.ok)throw new Error((await r.json()).error);setRows(old=>old.map(e=>e.id===id?{...e,status:value}:e));}catch(e){setError(e instanceof Error?e.message:'Could not update enquiry.');}}
  const filtered=rows.filter(r=>(status==='All'||r.status===status)&&`${r.id} ${r.name} ${r.company} ${r.email} ${r.location}`.toLowerCase().includes(query.toLowerCase()));
  function exportCSV(){const safe=(v:string)=>{const value=/^[=+@-]/.test(v)?`'${v}`:v;return `"${value.replaceAll('"','""')}"`;};const lines=[['Reference','Created','Name','Company','Email','Phone','Location','Duration','Status'].join(','),...filtered.map(r=>[r.id,r.created_at,r.name,r.company,r.email,r.phone,r.location,r.duration,r.status].map(safe).join(','))];const url=URL.createObjectURL(new Blob([lines.join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='aggcon-enquiries.csv';a.click();URL.revokeObjectURL(url);}
  if(!auth)return <section className="admin-login container"><LockKeyhole size={36}/><h1>ENQUIRY STUDIO.</h1><p>A private space for your project conversations.</p><form onSubmit={login}><label>Admin passphrase<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button button-orange" disabled={loading}>{loading?'Connecting…':'Sign in'}{loading?<Loader2 size={18} className="spin"/>:<ArrowRight size={18}/>}</button>{error&&<p className="form-error" role="alert">{error}</p>}</form><p className="detail-note">Use the admin passphrase configured for this local installation.</p></section>;
  return <section className="admin-page container"><div className="page-intro"><div><h1>ENQUIRY STUDIO.</h1><p>Your project conversations, in one place.</p></div><button className="inline-link" onClick={async()=>{await fetch('/api/admin',{method:'DELETE'});setAuth(false);setRows([]);}}>Sign out <LogOut size={17}/></button></div><div className="admin-summary"><div><strong>{rows.length}</strong><span>Total enquiries</span></div><div><strong>{rows.filter(r=>r.status==='New').length}</strong><span>New conversations</span></div><div><strong>{rows.filter(r=>r.status==='Contacted').length}</strong><span>Contacted</span></div></div><div className="admin-tools"><div className="resource-search"><Search size={17}/><input placeholder="Search enquiries…" aria-label="Search enquiries" value={query} onChange={e=>setQuery(e.target.value)}/></div><label>Status <select value={status} onChange={e=>setStatus(e.target.value)}>{['All','New','In review','Contacted','Closed'].map(s=><option key={s}>{s}</option>)}</select></label><button className="inline-link" onClick={exportCSV}>Export CSV <ArrowDownToLine size={17}/></button></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="enquiry-list">{filtered.length?filtered.map(r=><article key={r.id} className="enquiry-card"><div className="enquiry-row"><button className="enquiry-open" onClick={()=>setSelected(selected===r.id?'':r.id)} aria-expanded={selected===r.id}><span>{r.id}<small>{new Date(r.created_at).toLocaleDateString('en-IN')} · {r.kind}</small></span><span>{r.company}<small>{r.name} · {r.location}</small></span><ChevronDown size={18}/></button><select aria-label={`Status for ${r.id}`} value={r.status} onChange={e=>void update(r.id,e.target.value)}>{['New','In review','Contacted','Closed'].map(s=><option key={s}>{s}</option>)}</select></div>{selected===r.id&&<div className="enquiry-details"><div><h3>Contact</h3><a href={`mailto:${r.email}`}>{r.email}</a><a href={`tel:${r.phone}`}>{r.phone}</a><h3>Project</h3><p>{r.location} · {r.duration}<br/>Start: {r.start_date||'To be discussed'}</p></div><div><h3>Equipment</h3>{JSON.parse(r.items).length?JSON.parse(r.items).map((i:{id:string;name:string;quantity:number})=><p key={i.id}>{i.name} × {i.quantity}</p>):<p>General enquiry</p>}<h3>Message</h3><p className="enquiry-message">{r.message||'No additional message.'}</p></div></div>}</article>):<div className="empty-state"><h2>{rows.length?'No matching enquiries.':'Your next conversation starts here.'}</h2><p>{rows.length?'Try another search or status.':'Submitted quote and contact requests will appear in this private dashboard.'}</p></div>}</div></section>;
}
