'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ChevronDown, Search, X, Menu, Plus, Phone, Mail, Check } from 'lucide-react';
import { categories, company, equipment, projects } from '@/lib/data';
import { useQuote } from './QuoteContext';
export function Wordmark(){return <span className="wordmark">AGGCON<span className="wordmark-dot" aria-hidden="true" /></span>;}
export function Header(){
  const pathname=usePathname(); const {items}=useQuote(); const [mega,setMega]=useState(false); const [search,setSearch]=useState(''); const [scrolled,setScrolled]=useState(false);
  const searchRef=useRef<HTMLDialogElement>(null); const menuRef=useRef<HTMLDialogElement>(null);
  useEffect(()=>{ const scroll=()=>setScrolled(window.scrollY>40); scroll(); window.addEventListener('scroll',scroll,{passive:true}); const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchRef.current?.showModal();}if(e.key==='Escape')setMega(false);};window.addEventListener('keydown',key);return()=>{window.removeEventListener('scroll',scroll);window.removeEventListener('keydown',key);};},[]);
  useEffect(()=>{setMega(false); menuRef.current?.close(); searchRef.current?.close();},[pathname]);
  const results=[...equipment.map(e=>({name:e.name,type:'Equipment',href:`/equipment/${e.id}`})),...projects.map(p=>({name:p.name,type:'Project',href:`/projects/${p.id}`}))].filter(r=>r.name.toLowerCase().includes(search.toLowerCase())).slice(0,8);
  const dark=pathname==='/'||pathname.startsWith('/projects/')||pathname==='/company';
  const nav=[['Industries','/industries'],['Projects','/projects'],['Company','/company']];
  return <>
    <header className={`site-header ${dark?'on-dark':''} ${scrolled?'scrolled':''}`}>
      <div className="header-inner"><Link href="/" className="logo" aria-label="AGGCON home"><Wordmark/></Link>
        <nav className="desktop-nav" aria-label="Main navigation"><button className={pathname.startsWith('/equipment')?'nav-link active':'nav-link'} onClick={()=>setMega(!mega)} aria-expanded={mega} aria-controls="equipment-menu">Equipment <ChevronDown size={13}/></button>{nav.map(([name,url])=><Link className={`nav-link ${pathname===url?'active':''}`} href={url} key={url}>{name}</Link>)}</nav>
        <div className="header-actions"><button className="search-trigger icon-button" aria-label="Search equipment and projects" onClick={()=>searchRef.current?.showModal()}><Search size={19}/></button><Link className="quote-header" href="/quote">Get a quote {items.length>0&&<span className="quote-count">{items.length}</span>}<ArrowUpRight size={17}/></Link><button className="mobile-menu-trigger icon-button" aria-label="Open navigation" onClick={()=>menuRef.current?.showModal()}><Menu size={24}/></button></div>
      </div>
      {mega&&<div id="equipment-menu" className="mega-menu"><div className="mega-intro"><h2>Built for your<br/>next big thing.</h2><Link href="/equipment" onClick={()=>setMega(false)}>Explore the entire fleet <ArrowUpRight size={18}/></Link></div><div className="mega-categories">{categories.map(c=><Link key={c.id} href={`/equipment?category=${c.id}`} onClick={()=>setMega(false)}>{c.full}<ArrowUpRight size={16}/></Link>)}</div><button className="mega-close icon-button" aria-label="Close equipment menu" onClick={()=>setMega(false)}><X size={20}/></button></div>}
    </header>
    <dialog ref={searchRef} className="search-dialog" onClick={e=>{if(e.target===e.currentTarget)searchRef.current?.close();}}><div className="search-panel"><div className="dialog-heading"><h2>What are you looking for?</h2><button className="icon-button" aria-label="Close search" onClick={()=>searchRef.current?.close()}><X size={23}/></button></div><div className="search-field"><Search size={21}/><input aria-label="Search equipment or projects" placeholder="Try a piling rig, JCB or Atal Setu…" value={search} onChange={e=>setSearch(e.target.value)} autoFocus/></div><div className="search-results">{results.length?results.map(r=><Link href={r.href} key={r.href} onClick={()=>searchRef.current?.close()}><span>{r.name}<small>{r.type}</small></span><ArrowUpRight size={20}/></Link>):<p>No matching machines or projects. Try another name or <Link href="/contact">talk to our team</Link>.</p>}</div></div></dialog>
    <dialog ref={menuRef} className="mobile-nav-dialog"><div className="mobile-nav-top"><Wordmark/><button className="icon-button" aria-label="Close navigation" onClick={()=>menuRef.current?.close()}><X size={27}/></button></div><nav aria-label="Mobile navigation">{[['Equipment','/equipment'],...nav,['Investors','/investors'],['Contact','/contact']].map(([name,url])=><Link href={url} key={url} onClick={()=>menuRef.current?.close()}>{name}<ArrowUpRight/></Link>)}</nav><Link href="/quote" className="button button-orange" onClick={()=>menuRef.current?.close()}>Plan your project <ArrowUpRight/></Link><a className="mobile-phone" href={`tel:${company.tel}`}>{company.phone}</a></dialog>
    {mega&&<button className="menu-scrim" aria-label="Close equipment navigation" onClick={()=>setMega(false)}/>}
  </>;
}
export function Footer(){return <footer className="site-footer"><div className="footer-cta"><h2>BIG IDEAS.<br/><span>LET’S BUILD THEM.</span></h2><Link className="round-link" href="/quote" aria-label="Start a project enquiry"><ArrowUpRight size={42}/></Link></div><div className="footer-main"><div className="footer-brand"><Link href="/" aria-label="AGGCON home"><Wordmark/></Link><p>Equipment. Expertise.<br/>A partner for what’s next.</p><a href={`tel:${company.tel}`}><Phone size={15}/>{company.phone}</a><a href={`mailto:${company.email}`}><Mail size={15}/>{company.email}</a></div><div><h3>Explore</h3><Link href="/equipment">Rent equipment</Link><Link href="/buy">Buy used equipment</Link><Link href="/industries">Industries</Link><Link href="/projects">Our projects</Link></div><div><h3>AGGCON</h3><Link href="/company">Our company</Link><Link href="/sustainability">Sustainability & CSR</Link><Link href="/news">News & recognition</Link><Link href="/investors">Investor relations</Link><a href="https://aggconequipments.com/careers/" target="_blank" rel="noreferrer">Careers</a></div><div className="footer-address"><h3>Let’s talk</h3><p>{company.corporate}</p><Link href="/contact" className="inline-link">Find your rental partner <ArrowUpRight size={16}/></Link><a href="https://www.linkedin.com/company/aggconequipments/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} AGGCON Equipments International Limited</span><div><Link href="/privacy">Privacy</Link><span>Website revamp concept by Athreix.</span></div></div></footer>;}
export function AddToQuote({id,compact=false}:{id:string;compact?:boolean}){const {items,add}=useQuote();const added=items.some(i=>i.id===id);return <button type="button" className={compact?'add-quote-button':'button button-orange'} onClick={()=>add(id)} aria-label={added?'Already in your quote list':`Add ${equipment.find(e=>e.id===id)?.name||'equipment'} to quote`} disabled={added}>{added?'Added to quote':compact?'Add to quote':'Add to your project'}{added?<Check size={17}/>:<Plus size={compact?17:20}/>}</button>;}
export function ArrowLink({href,children,className=''}:{href:string;children:React.ReactNode;className?:string}){return <Link href={href} className={`inline-link ${className}`}>{children}<ArrowUpRight size={19}/></Link>;}
