'use client';
import { assetUrl } from '@/lib/preview';
import Link from 'next/link';
import { useRef, useState, useEffect } from 'react';
import { ArrowUpRight, ArrowDown, ArrowRight, MoveUpRight, MapPin, Wrench, HardHat, Truck } from 'lucide-react';
import { categories, projects } from '@/lib/data';
import { ArrowLink } from './Chrome';
export function Home(){
  const hero=useRef<HTMLElement>(null); const [active,setActive]=useState(0);const category=categories[active];
  useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const el=hero.current;if(!el)return;let pointerFrame=0,scrollFrame=0;const move=(e:PointerEvent)=>{cancelAnimationFrame(pointerFrame);pointerFrame=requestAnimationFrame(()=>{const box=el.getBoundingClientRect();el.style.setProperty('--mx',`${(e.clientX-box.left-box.width/2)*.006}px`);el.style.setProperty('--my',`${(e.clientY-box.top-box.height/2)*.008}px`);});};const scroll=()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=0;const progress=Math.max(0,Math.min(1,window.scrollY/el.offsetHeight));el.style.setProperty('--hero-scale',String(1.03+progress*.06));el.style.setProperty('--hero-scroll',`${progress*18}px`);});};scroll();el.addEventListener('pointermove',move);window.addEventListener('scroll',scroll,{passive:true});return()=>{el.removeEventListener('pointermove',move);window.removeEventListener('scroll',scroll);cancelAnimationFrame(pointerFrame);cancelAnimationFrame(scrollFrame);};},[]);
  return <>
    <section className="hero" ref={hero}><div className="hero-visual"><img src={assetUrl('/images/hero-machinery.webp')} alt="Cinematic concept image of orange construction machinery at a worksite" fetchPriority="high"/></div><div className="hero-shade"/><div className="hero-content container"><h1>POWERING<br/>WHAT’S<br/><span>NEXT.</span></h1><p>The right equipment. The right expertise.<br/>A rental partner for your biggest ambitions.</p><div className="hero-actions"><Link href="/equipment" className="button button-orange">Explore our fleet <ArrowUpRight size={20}/></Link><Link href="/quote" className="hero-secondary">Let’s talk about your project <ArrowRight size={18}/></Link></div></div><div className="hero-bottom container"><div><span className="status-dot"/> Infrastructure equipment rental, since 2003</div><a href="#fleet" className="hero-scroll">Built to go further <ArrowDown size={17}/></a></div><div className="hero-vertical" aria-hidden="true">THE WORK NEVER STOPS. NEITHER DO WE.</div></section>
    <section className="intro-section container"><div className="intro-heading"><h2>WHEN YOUR PROJECT<br/>THINKS BIG,<br/><span>SO DO WE.</span></h2></div><div className="intro-copy"><p className="large-copy">From the first foundation to the final lift. We bring the machines, the people and the commitment to keep your project moving.</p><p>AGGCON is an infrastructure equipment rental partner with operations across India. Our diverse fleet, skilled operators and maintenance teams work together to turn complex requirements into dependable solutions.</p><ArrowLink href="/company">Meet your rental partner</ArrowLink></div></section>
    <section className="fleet-section" id="fleet"><div className="container"><div className="section-heading"><h2>BIG WORK.<br/><span>RIGHT EQUIPMENT.</span></h2><ArrowLink href="/equipment">Explore the fleet</ArrowLink></div><div className="fleet-showcase"><div className="category-rail" role="tablist" aria-label="Fleet categories">{categories.map((c,i)=><button key={c.id} role="tab" aria-selected={i===active} aria-controls="fleet-panel" id={`tab-${c.id}`} tabIndex={i===active?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowRight'){e.preventDefault();const n=(i+1)%categories.length;setActive(n);document.getElementById(`tab-${categories[n].id}`)?.focus();}if(e.key==='ArrowUp'||e.key==='ArrowLeft'){e.preventDefault();const n=(i+categories.length-1)%categories.length;setActive(n);document.getElementById(`tab-${categories[n].id}`)?.focus();}}} className={i===active?'selected':''}><span>{c.name}</span><ArrowUpRight size={23}/></button>)}</div><div className={`category-stage ${category.id}`} id="fleet-panel" role="tabpanel" aria-labelledby={`tab-${category.id}`}><div className="category-photo" key={category.id}><img src={category.image} alt={`${category.full} from AGGCON's published fleet`} loading="lazy"/></div><div className="category-details"><h3>{category.title}</h3><p>{category.description}</p><Link href={`/equipment?category=${category.id}`} className="category-link">Explore {category.name.toLowerCase()} <ArrowUpRight size={23}/></Link></div><span className="category-word" aria-hidden="true">{category.name}</span></div></div></div></section>
    <div className="brand-belt" aria-hidden="true"><div>BUILT FOR THE BIG PICTURE. <span>BUILT FOR THE BIG PICTURE.</span> BUILT FOR THE BIG PICTURE. <span>BUILT FOR THE BIG PICTURE.</span></div></div>
    <section className="projects-section container"><div className="section-heading"><h2>PART OF SOMETHING<br/><span>BIGGER.</span></h2><div><p>Landmark projects.<br/>A dependable partner behind the progress.</p><ArrowLink href="/projects">Explore our work</ArrowLink></div></div><div className="project-mosaic"><Link className="project-feature" href="/projects/atal-setu"><img src={assetUrl('/images/atal-setu-wide.webp')} alt="Atal Setu bridge connecting Mumbai and Navi Mumbai" loading="lazy"/><div className="project-image-shade"/><div className="project-feature-top"><span>Bridges & infrastructure</span><span>Mumbai, India</span></div><div className="project-feature-copy"><h3>ATAL SETU</h3><p>Equipment and operators for a landmark connection.</p><span className="project-circle"><ArrowUpRight size={27}/></span></div></Link><div className="project-side">{projects.slice(1,3).map(p=><Link className="project-small" href={`/projects/${p.id}`} key={p.id}><div className="project-small-image"><img src={p.image} alt={p.name} loading="lazy"/></div><div><h3>{p.name}</h3><span>{p.sector}</span><ArrowUpRight size={23}/></div></Link>)}</div></div></section>
    <section className="partner-section"><div className="partner-image"><img src={assetUrl('/images/operator.webp')} alt="AGGCON-branded construction machinery and an operator" loading="lazy"/><span>Equipment is only half the story.</span></div><div className="partner-content"><h2>GOOD MACHINES.<br/><span>GREAT PEOPLE.</span></h2><p className="large-copy">The real difference is the team<br/>that keeps you going.</p><p>We bring skilled operators, maintenance expertise and project coordination together—so your equipment works as hard as your ambitions.</p><div className="support-list"><div><HardHat size={22}/><span>Skilled operators</span></div><div><Wrench size={22}/><span>Maintenance support</span></div><div><Truck size={22}/><span>Deployment coordination</span></div></div><ArrowLink href="/industries">Find a solution for your industry</ArrowLink></div></section>
    <section className="forward-section container"><div><h2>PROGRESS WITH<br/><span>PURPOSE.</span></h2><p>Infrastructure connects communities.<br/>We believe our impact should go further.</p><ArrowLink href="/sustainability">Discover our CSR initiatives</ArrowLink></div><div className="purpose-statement"><span className="purpose-leaf" aria-hidden="true"><svg viewBox="0 0 140 140"><path d="M28 110C11 47 55 24 119 23c-4 65-22 107-79 95"/><path d="M27 119 97 48M52 92l-4-30M75 70l28 2"/></svg></span><h3>Growing a better<br/>tomorrow. Together.</h3><p>Tree of Friendship. Women’s empowerment.<br/>The well-being of the communities around us.</p></div></section>
  </>;
}
