'use client';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import { ArrowUpRight, ArrowRight, ArrowLeft, Check, Trash2, Minus, Plus, Loader2, CheckCircle2, Phone } from 'lucide-react';
import { equipment, company } from '@/lib/data';
import { useQuote } from './QuoteContext';
import { MachineImage } from './Fleet';
import { staticPreview } from '@/lib/preview';
type FormFields={name:string;email:string;phone:string;company:string;location:string;startDate:string;duration:string;message:string;website:string;consent:boolean};
const blank:FormFields={name:'',email:'',phone:'',company:'',location:'',startDate:'',duration:'1–3 months',message:'',website:'',consent:false};
export function QuoteForm({contact=false}:{contact?:boolean}){
  const {items,remove,quantity,clear,ready}=useQuote();const [step,setStep]=useState(contact?1:0);const [fields,setFields]=useState(blank);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reference,setReference]=useState('');const [restored,setRestored]=useState(false);
  useEffect(()=>{try{const d=JSON.parse(sessionStorage.getItem('aggcon-enquiry-draft')||'null');if(d&&typeof d.name==='string')setFields({...blank,...d,consent:false});}catch{}setRestored(true);},[]);
  useEffect(()=>{if(restored)sessionStorage.setItem('aggcon-enquiry-draft',JSON.stringify(fields));},[fields,restored]);
  const update=(key:keyof FormFields,value:string|boolean)=>setFields(old=>({...old,[key]:value}));
  const validateProject=()=>{if(fields.location.trim().length<2){setError('Please enter your project location.');return false;}if(fields.startDate&&fields.startDate<new Date().toISOString().slice(0,10)){setError('Please choose a start date today or later.');return false;}setError('');return true;};
  const enquiryText=()=>[`AGGCON equipment enquiry · ${reference}`,`Name: ${fields.name}`,`Company: ${fields.company}`,`Email: ${fields.email}`,`Phone: ${fields.phone}`,`Project location: ${fields.location}`,`Start: ${fields.startDate||'To be discussed'}`,`Rental period: ${fields.duration}`,'','Equipment:',...(contact||!items.length?['General enquiry']:items.map(i=>`${equipment.find(e=>e.id===i.id)?.name} × ${i.quantity}`)),'',fields.message,'','Prepared using the Athreix website revamp preview. Availability and terms require AGGCON confirmation.'].join('\n');
  const downloadEnquiry=()=>{const url=URL.createObjectURL(new Blob([enquiryText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`aggcon-enquiry-${reference}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!validateProject()){setStep(1);return;}if(fields.name.trim().length<2||fields.company.trim().length<2){setError('Please enter your name and company.');return;}if(!/^[+\d\s()-]{7,24}$/.test(fields.phone)){setError('Please enter a valid phone number.');return;}if(!fields.consent){setError('Please agree to the enquiry privacy notice.');return;}setError('');if(staticPreview){setReference(`DRAFT-${crypto.randomUUID().slice(0,8).toUpperCase()}`);return;}setBusy(true);try{const response=await fetch('/api/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,kind:contact?'contact':'quote',items:contact?[]:items})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');setReference(data.id);if(!contact)clear();sessionStorage.removeItem('aggcon-enquiry-draft');}catch(e){setError(e instanceof Error?e.message:'We could not save your enquiry. Please try again.');}finally{setBusy(false);}};
  if(reference)return <div className="quote-success"><CheckCircle2 size={58}/><h2>GOOD THINGS<br/><span>START HERE.</span></h2><p>{staticPreview?'Your enquiry is ready to share.':`Your ${contact?'message':'project enquiry'} has been saved.`}</p><div className="reference-box"><span>{staticPreview?'Your draft reference':'Your reference'}</span><strong>{reference}</strong></div><p className="success-note">{staticPreview?'Download your enquiry or review it in your email app. Nothing has been sent yet. AGGCON will confirm equipment availability and rental terms.':'This local preview stores your enquiry on this computer. For an actual rental request, contact AGGCON directly.'}</p><div>{staticPreview?<><a href={`mailto:${company.email}?subject=${encodeURIComponent(`Equipment enquiry — ${fields.company}`)}&body=${encodeURIComponent(enquiryText())}`} className="button button-orange">Review email draft <ArrowUpRight size={19}/></a><button className="inline-link" onClick={downloadEnquiry}>Download enquiry <ArrowRight size={18}/></button></>:<Link href="/equipment" className="button button-dark">Explore more equipment <ArrowUpRight size={19}/></Link>}<a href={`tel:${company.tel}`} className="inline-link">Call AGGCON <Phone size={17}/></a></div></div>;
  return <div className="quote-workspace"><div className="quote-main">{!contact&&<ol className="quote-steps" aria-label="Enquiry steps">{['Your equipment','Project details','Your details'].map((s,i)=><li key={s} className={step===i?'current':step>i?'done':''}><button type="button" onClick={()=>{if(i<step||i===0||i===1){setError('');setStep(i);}}} disabled={i>step&&i===2}><span>{step>i?<Check size={13}/>:i+1}</span>{s}</button></li>)}</ol>}
    <form onSubmit={submit}>
      {step===0&&!contact&&<><div className="form-section-heading"><h2>Your project shortlist</h2><p>Add machines from the fleet, or tell us your requirements in the next step.</p></div>{ready&&items.length?items.map(item=>{const machine=equipment.find(e=>e.id===item.id)!;return <div className="quote-machine" key={item.id}><div className="quote-machine-image"><MachineImage machine={machine}/></div><div className="quote-machine-name"><span>{machine.type}</span><Link href={`/equipment/${machine.id}`}>{machine.name}</Link></div><div className="quantity-control"><button type="button" aria-label={`Decrease ${machine.name} quantity`} disabled={item.quantity===1} onClick={()=>quantity(item.id,item.quantity-1)}><Minus size={14}/></button><span aria-label="Quantity">{item.quantity}</span><button type="button" aria-label={`Increase ${machine.name} quantity`} disabled={item.quantity===100} onClick={()=>quantity(item.id,item.quantity+1)}><Plus size={14}/></button></div><button type="button" className="icon-button remove-machine" aria-label={`Remove ${machine.name}`} onClick={()=>remove(item.id)}><Trash2 size={17}/></button></div>;}):<div className="quote-empty"><h3>Every project starts with a possibility.</h3><p>Explore our fleet to add machines, or continue with a general equipment enquiry.</p><Link href="/equipment" className="inline-link">Explore the fleet <ArrowUpRight size={18}/></Link></div>}<Link href="/equipment" className="add-more"><Plus size={17}/> Add more equipment</Link><div className="form-actions"><span>Availability confirmed by our team.</span><button type="button" className="button button-orange" onClick={()=>setStep(1)}>Project details <ArrowRight size={19}/></button></div></>}
      {(step===1||contact)&&<><div className="form-section-heading"><h2>{contact?'Tell us what you have in mind.':'A little about your project.'}</h2><p>Help us understand the work ahead.</p></div><div className="form-grid"><label>Project location <span>*</span><input name="location" placeholder="City, state or project site" required value={fields.location} onChange={e=>update('location',e.target.value)}/></label><label>Expected rental period<select name="duration" value={fields.duration} onChange={e=>update('duration',e.target.value)}>{['Less than 1 month','1–3 months','3–6 months','6–12 months','More than 12 months','To be discussed'].map(d=><option key={d}>{d}</option>)}</select></label><label>Expected start date<input name="startDate" type="date" min={new Date().toISOString().slice(0,10)} value={fields.startDate} onChange={e=>update('startDate',e.target.value)}/></label><label className="full-width">What are you building?<textarea name="message" rows={4} maxLength={4000} placeholder="Project scope, machine requirements, capacity, site conditions or anything we should know…" value={fields.message} onChange={e=>update('message',e.target.value)}/></label></div>{!contact&&<div className="form-actions"><button type="button" className="back-button" onClick={()=>{setError('');setStep(0);}}><ArrowLeft size={17}/> Your equipment</button><button type="button" className="button button-orange" onClick={()=>{if(validateProject())setStep(2);}}>Your details <ArrowRight size={19}/></button></div>}</>}
      {(step===2||contact)&&<><div className="form-section-heading"><h2>Let’s make the connection.</h2><p>Who should our team speak with?</p></div><div className="form-grid"><label>Full name <span>*</span><input name="name" autoComplete="name" placeholder="Your full name" required minLength={2} maxLength={100} value={fields.name} onChange={e=>update('name',e.target.value)}/></label><label>Company <span>*</span><input name="company" autoComplete="organization" placeholder="Company name" required minLength={2} maxLength={200} value={fields.company} onChange={e=>update('company',e.target.value)}/></label><label>Work email <span>*</span><input name="email" type="email" autoComplete="email" placeholder="you@company.com" required maxLength={200} value={fields.email} onChange={e=>update('email',e.target.value)}/></label><label>Phone number <span>*</span><input name="phone" type="tel" autoComplete="tel" placeholder="+91" required minLength={7} maxLength={24} value={fields.phone} onChange={e=>update('phone',e.target.value)}/></label></div><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off" value={fields.website} onChange={e=>update('website',e.target.value)}/></label></div><label className="consent-label"><input name="consent" type="checkbox" checked={fields.consent} onChange={e=>update('consent',e.target.checked)} required/><span>I agree to the <Link href="/privacy">privacy notice</Link> and to being contacted about my enquiry.</span></label><div className="form-actions">{!contact?<button type="button" className="back-button" onClick={()=>{setError('');setStep(1);}}><ArrowLeft size={17}/> Project details</button>:<span>Fields marked * are required.</span>}<button type="submit" className="button button-orange" disabled={busy}>{busy?'Saving your enquiry…':staticPreview?'Prepare enquiry':contact?'Send your message':'Send project enquiry'}{busy?<Loader2 className="spin" size={19}/>:<ArrowUpRight size={19}/>}</button></div></>}
      {error&&<p className="form-error" role="alert">{error}</p>}
    </form></div><aside className="quote-aside"><h3>YOUR NEXT BIG THING<br/>STARTS WITH US.</h3><p>Equipment. Operators. Maintenance.<br/>A partner for the entire project.</p><div className="quote-aside-line"/><p>Prefer a conversation?</p><a className="aside-phone" href={`tel:${company.tel}`}>{company.phone}<ArrowUpRight size={21}/></a><a href={`mailto:${company.email}`}>{company.email}</a><p className="local-preview-note">{staticPreview?'Prepare your enquiry, then review and share it by email or download.':'Local presentation preview. Enquiries are saved locally and can be reviewed in the private dashboard.'}</p></aside></div>;
}
